
services:
  # PHP Service
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: eyantra-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    networks:
      - eyantra-network
    depends_on:
      - db

  # Nginx Service for Backend
  webserver:
    image: nginx:alpine
    container_name: eyantra-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./backend:/var/www
      - ./backend/.docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - eyantra-network
    depends_on:
      - app

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: eyantra-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-eyantra}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-eyantra}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3306:3306"
    volumes:
      - eyantra-data:/var/lib/mysql
    networks:
      - eyantra-network

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: eyantra-frontend
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - eyantra-network
    environment:
      - VUE_APP_API_URL=http://localhost:8000/api
    depends_on:
      - webserver

networks:
  eyantra-network:
    driver: bridge

volumes:
  eyantra-data:
    driver: local